# Endpoints
OPSWAT_FILESCAN_ENDPOINT_USERINFO = '/api/users/me'
OPSWAT_FILESCAN_ENDPOINT_SCAN_FILE = '/api/scan/file'
OPSWAT_FILESCAN_ENDPOINT_SCAN_URL = '/api/scan/url'
OPSWAT_FILESCAN_ENDPOINT_SCAN_POLL = '/api/scan/{id}/report?{filters}'
OPSWAT_FILESCAN_ENDPOINT_SERACH = '/api/reports/search'
OPSWAT_FILESCAN_ENDPOINT_REPUTATION = '/api/reputation'

OPSWAT_FILESCAN_POLL_INTERVAL_MIN = 1
OPSWAT_FILESCAN_TIMEOUT_MIN = 30
OPSWAT_FILESCAN_POLL_INTERVAL_MAX = 30
OPSWAT_FILESCAN_TIMEOUT_MAX = 300